SELECT M.NAME
FROM 
(
    SELECT S.ID, S.NAME, P.SALARY
    FROM STUDENTS AS S
    JOIN PACKAGES AS P
    ON S.ID = P.ID
) AS M
JOIN FRIENDS AS F
ON M.ID = F.ID
JOIN PACKAGES AS P
ON F.FRIEND_ID = P.ID
WHERE M.SALARY < P.SALARY
ORDER BY P.SALARY;